name              'settings_for_running_rails_app'
maintainer        'Optimis'
maintainer_email  'sadfsdfsdfs@dsfsdf.sf'
license           'Apache 2.0'
description       'permission setting'
version           '0.0.2'
